import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import ProgressLoaderProvider from "@/components/providers/ProgressProvider";
import WarningDialog from "@/components/WarningDialog";
import PublicLayout from "@/components/layouts/PublicLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ReactQueryProvider>
            <ProgressLoaderProvider>
           <PublicLayout>
               {children}
           </PublicLayout>
              <Toaster position="top-right" />
              <WarningDialog/>
            </ProgressLoaderProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
