import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import ProgressLoaderProvider from "@/components/providers/ProgressProvider";
import WarningDialog from "@/components/WarningDialog";
import PublicLayout from "@/components/layouts/PublicLayout";
import localFont from "next/font/local";

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`  antialiased`}
      >
        <ThemeProvider>
          <ReactQueryProvider>
            <ProgressLoaderProvider>
              <PublicLayout>{children}</PublicLayout>
              <Toaster position="top-right" />
              <WarningDialog />
            </ProgressLoaderProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
